server:
  port: 8093

spring:
  application:
    name: websocket-101-demo

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    com.demo.websocket101: INFO
