name: Issue management - run stale action

on:
  schedule:
    # hourly at minute 23
    - cron: "23 * * * *"

permissions:
  contents: read

jobs:
  stale:
    permissions:
      issues: write  # for actions/stale to close stale issues
      pull-requests: write  # for actions/stale to close stale PRs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@28ca1036281a5e5922ead5184a1bbf96e5fc984e # v9.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          # TODO (trask) update back to 7 days after end of year break
          days-before-stale: 21
          days-before-close: 7
          only-labels: "needs author feedback"
          stale-issue-label: stale
          stale-issue-message: >
            This has been automatically marked as stale because it has been marked
            as needing author feedback and has not had any activity for 7 days.
            It will be closed automatically if there is no response from the author
            within 7 additional days from this comment.
          stale-pr-label: stale
          stale-pr-message: >
            This has been automatically marked as stale because it has been marked
            as needing author feedback and has not had any activity for 7 days.
            It will be closed automatically if there is no response from the author
            within 7 additional days from this comment.
